Repository Juinjang/Spring, pull requests merged in 2024-02, with the labels that each got.

#101 Fix/#94 체크리스트 관련 여러가지를 수정...
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistQuestionConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerResponseDTO.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistQuestionDTO.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistAnswer.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistAnswerOption.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistQuestion.java
  src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionType.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerOptionRepository.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistQuestionRepository.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
Labels: 🔥 hotFix, 코난

#103 [refactor/#102] 임장 전체보기 api 수정
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/controller/ImageController.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangMainListConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangMainViewListResponsetDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListResponseDTO.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangSort.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#104 [comment/#102] 메인화면 api 로그 추가
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: 💬 comment, 진, 👊🏻 PULL REQUEST
