Repository Juinjang/Spring, pull requests merged in 2024-05, with the labels that each got.

#131 [fix/#128] 검색 쿼리 고침
  .gitignore
  build.gradle
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepositoryImpl.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ✨ feature, ♻️ refactor, 🐞 bugFix, 진

#136 [fix/#133] 임장검색 멤버 검증 오류 고침
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepositoryImpl.java
  src/main/java/umc/th/juinjang/repository/limjang/dto/LimjangMainListDBResponsetDto.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ♻️ refactor, 🐞 bugFix, 진, 👊🏻 PULL REQUEST

#138 Feat/#137
  build.gradle
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistQuestionConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerRequestDTO.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistAnswer.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistAnswerOption.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistQuestionShort.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerOptionRepository.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistQuestionRepository.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
Labels: ♻️ refactor, 코난

#140 [Refactor/#132] 스크랩 API POST/DELETE로 나눔
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/controller/ScrapController.java
  src/main/java/umc/th/juinjang/model/entity/Scrap.java
  src/main/java/umc/th/juinjang/repository/limjang/ScrapRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangRetriever.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapRetriever.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapService.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapServiceImpl.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#152 fix: checklist answer response fix
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerResponseDTO.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
Labels: 🔥 hotFix, 코난
