Repository Juinjang/Spring, pull requests merged in 2024-12, with the labels that each got.

#254 refactor(#253) added s3 login in withdraw
  src/main/java/umc/th/juinjang/repository/limjang/LimjangPriceRepository.java
  src/main/java/umc/th/juinjang/repository/record/RecordRepository.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: ♻️ refactor

#255 [deploy] dev > prod
  src/main/java/umc/th/juinjang/repository/limjang/LimjangPriceRepository.java
  src/main/java/umc/th/juinjang/repository/record/RecordRepository.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: 🌏 deploy

#258 [deploy] dev > prod
  src/main/java/umc/th/juinjang/repository/image/ImageRepository.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: 🌏 deploy

#262 [feat/#256] : 시큐리티 whitelist 수정
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#264 [deploy] dev > prod
  build.gradle
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
Labels: 🌏 deploy, 진, 👊🏻 PULL REQUEST

#265 [refactor/#251] 스크랩 리팩토링
  src/main/java/umc/th/juinjang/controller/ScrapController.java
  src/main/java/umc/th/juinjang/model/entity/Scrap.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/ScrapRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangRetriever.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapRetriever.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapService.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapServiceImpl.java
  src/main/java/umc/th/juinjang/service/recordService/RecordService.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#266 [deploy] dev > prod
  src/main/java/umc/th/juinjang/controller/ScrapController.java
  src/main/java/umc/th/juinjang/model/entity/Scrap.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/ScrapRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangRetriever.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapRetriever.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapService.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapServiceImpl.java
  src/main/java/umc/th/juinjang/service/recordService/RecordService.java
Labels: 🌏 deploy
