Repository Juinjang/Spring, pull requests merged in 2024-09, with the labels that each got.

#206 Fix/#199
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/controller/OAuthController.java
  src/main/java/umc/th/juinjang/model/dto/auth/kakao/KakaoSignUpRequestDto.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: 🔥 hotFix, 여니, 👊🏻 PULL REQUEST

#202 [feat/#200] discord 알림 구현
  .gitignore
  build.gradle
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/external/discord/DiscordAlertProvider.java
  src/main/java/umc/th/juinjang/external/discord/DiscordFeignClient.java
  src/main/java/umc/th/juinjang/external/discord/dto/DiscordAlert.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#211 [refactor/#201] 메인화면 조회 API 리팩토링
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangMainListConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangsMainGetResponseConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/response/LimjangMainViewListResponsetDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/response/LimjangsMainGetResponse.java
  src/main/java/umc/th/juinjang/model/entity/Scrap.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepositoryImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: 진, 👊🏻 PULL REQUEST

#229 [feat/#228] 임장 상세주소 필드 nullable로 변경
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangPostRequestConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/request/LimjangPostRequest.java
  src/main/java/umc/th/juinjang/model/dto/limjang/request/LimjangPostRequestDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java
Labels: ✨ feature, 진

#231 [refactor/#230] 임장 일괄삭제 리팩토링
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/model/dto/limjang/request/LimjangDeleteRequestDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/request/LimjangsDeleteRequest.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangRetriever.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST
