Repository Juinjang/Spring, pull requests merged in 2024-01, with the labels that each got.

#4 [add/#3] 엔티티 셋팅
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/domain/ChecklistAnswer.java
  src/main/java/umc/th/juinjang/domain/ChecklistQuestion.java
  src/main/java/umc/th/juinjang/domain/Image.java
  src/main/java/umc/th/juinjang/domain/Limjang.java
  src/main/java/umc/th/juinjang/domain/LimjangPrice.java
  src/main/java/umc/th/juinjang/domain/Member.java
  src/main/java/umc/th/juinjang/domain/Record.java
  src/main/java/umc/th/juinjang/domain/Report.java
  src/main/java/umc/th/juinjang/domain/Scrap.java
  src/main/java/umc/th/juinjang/domain/common/BaseEntity.java
  src/main/java/umc/th/juinjang/domain/enums/ChecklistQuestionCategory.java
  src/main/java/umc/th/juinjang/domain/enums/ChecklistQuestionType.java
  src/main/java/umc/th/juinjang/domain/enums/ChecklistQuestionVersion.java
  src/main/java/umc/th/juinjang/domain/enums/LimjangPriceType.java
  src/main/java/umc/th/juinjang/domain/enums/LimjangPropertyType.java
  src/main/java/umc/th/juinjang/domain/enums/LimjangPurpose.java
  src/main/java/umc/th/juinjang/domain/enums/MemberProvider.java
Labels: ➕ add, ✨ feature, 진

#7 [refactor/#6] : 엔티티 필드명 변경, enum에 기능 추가
  build.gradle
  src/main/java/umc/th/juinjang/converter/limjang/LimjangPostConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangPostRequest.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangPostResponse.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangPriceType.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangPropertyType.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangPurpose.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ✨ feature, ♻️ refactor, 진

#14 [feat/#11] 메인화면 리스트 출력 api
  src/main/java/umc/th/juinjang/apiPayload/ApiResponse.java
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/th/juinjang/apiPayload/exception/handler/LimjangHandler.java
  src/main/java/umc/th/juinjang/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/th/juinjang/apiPayload/exception/handler/ScrapHandler.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/controller/ScrapController.java
  src/main/java/umc/th/juinjang/converter/ScrapConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangMainListConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangPostConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangMainViewListResponsetDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangPostRequest.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangPostRequestDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangPostResponseDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListRequestDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListResponseDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/model/entity/LimjangPrice.java
  src/main/java/umc/th/juinjang/model/entity/Scrap.java
  src/main/java/umc/th/juinjang/model/entity/common/BaseEntity.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangPriceType.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangPropertyType.java
  src/main/java/umc/th/juinjang/model/entity/enums/LimjangPurpose.java
  src/main/java/umc/th/juinjang/model/entity/enums/ScrapActionType.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangPriceRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/MemberRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/ScrapRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapCommandService.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapCommandServiceImpl.java
  src/main/java/umc/th/juinjang/utils/LimjangUtil.java
  src/main/java/umc/th/juinjang/validation/annotation/VaildPriceListSize.java
  src/main/java/umc/th/juinjang/validation/validator/PriceListVaildation.java
Labels: ➕ add, ✨ feature, 진, 👊🏻 PULL REQUEST

#20 [feat/#16] 체크리스트 질문 목록 버전별 조회
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/apiPayload/exception/handler/ChecklistHandler.java
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistQuestionConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistQuestionDTO.java
  src/main/java/umc/th/juinjang/model/entity/ChecklistQuestion.java
  src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionCategory.java
  src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionType.java
  src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionVersion.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerRepository.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistQuestionRepository.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
Labels: ✨ feature, 코난

#26 [feat/#23] 체크리스트 답변 저장 및 조회
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerRequestDTO.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerResponseDTO.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerRepository.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
Labels: ✨ feature, 코난

#30 [feat/#27] 체크리스트 수정 로직 추가
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerRepository.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
Labels: ✨ feature, 코난

#35 [feat/#33] add report calc logic
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerAndReportResponseDTO.java
  src/main/java/umc/th/juinjang/model/entity/Report.java
  src/main/java/umc/th/juinjang/repository/checklist/ReportRepository.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
Labels: ✨ feature, 코난

#42 [feat/#15] 임장 선택 삭제 구현
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/controller/ScrapController.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangDeleteRequestDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/model/entity/Scrap.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/ScrapRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ScrapService/ScrapCommandServiceImpl.java
Labels: ✨ feature, ♻️ refactor, 진, 👊🏻 PULL REQUEST

#43 [Feat/#13] 임장 검색 구현
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListRequestDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListResponseDTO.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ✨ feature, ♻️ refactor, 진, 👊🏻 PULL REQUEST

#47 [feat/#46] 임장 수정 구현
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangPostConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangUpdateConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangUpdateRequestDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/model/entity/LimjangPrice.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java
  src/main/java/umc/th/juinjang/utils/LimjangUtil.java
Labels: ➕ add, ✨ feature, 진, 👊🏻 PULL REQUEST

#50 [feat/#48] 이미지 업로드 구현 완료
  src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/controller/ImageController.java
  src/main/java/umc/th/juinjang/converter/ImageUploadConverter.java
  src/main/java/umc/th/juinjang/model/dto/image/ImageUploadRequestDTO.java
  src/main/java/umc/th/juinjang/model/dto/image/ImageUploadResponseDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/repository/image/ImageRepository.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageCommandService.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageQueryService.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/S3Uploader.java
Labels: ➕ add, ✨ feature, 진, 👊🏻 PULL REQUEST

#54 fix: report return response
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerAndReportResponseDTO.java
  src/main/java/umc/th/juinjang/model/dto/checklist/ReportResponseDTO.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
Labels: 🔥 hotFix, 코난

#56 [fix/#51] 사진 업로드 문제 해결
  src/main/java/umc/th/juinjang/controller/ImageController.java
  src/main/java/umc/th/juinjang/converter/image/ImageListConverter.java
  src/main/java/umc/th/juinjang/converter/image/ImageUploadConverter.java
  src/main/java/umc/th/juinjang/model/dto/image/ImageListResponseDTO.java
  src/main/java/umc/th/juinjang/repository/image/ImageRepository.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageQueryService.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/S3Uploader.java
Labels: ➕ add, ✨ feature, 진

#57 [feat/#55] record 조회
  src/main/java/umc/th/juinjang/controller/RecordController.java
  src/main/java/umc/th/juinjang/converter/record/RecordConverter.java
  src/main/java/umc/th/juinjang/model/dto/record/RecordResponseDTO.java
  src/main/java/umc/th/juinjang/model/entity/Record.java
  src/main/java/umc/th/juinjang/repository/record/RecordRepository.java
  src/main/java/umc/th/juinjang/service/recordService/RecordService.java
Labels: ✨ feature, 코난

#58 [feat/#52] 사진 선택 삭제 구현
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/apiPayload/exception/handler/S3Handler.java
  src/main/java/umc/th/juinjang/controller/ImageController.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageCommandService.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/S3Uploader.java
Labels: ➕ add, ✨ feature, 진

#62 fix(#16) : 카카오 로그인 수정
  src/main/java/umc/th/juinjang/model/dto/auth/kakao/KakaoUser.java
  src/main/java/umc/th/juinjang/model/entity/Member.java
  src/main/java/umc/th/juinjang/service/auth/KakaoOauth.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: ✨ feature, 여니, 👊🏻 PULL REQUEST

#65 [feat/#59] 임장-리포트 연결
  src/main/java/umc/th/juinjang/converter/limjang/LimjangMainListConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListResponseDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/S3Service.java
Labels: ✨ feature, 👊🏻 PULL REQUEST

#70 [refactor/#67] 응답값 of-> onSuccess로 통일
  src/main/java/umc/th/juinjang/controller/ImageController.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/controller/ScrapController.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#72 [refactor/#67] : @PathVariable에 name 붙임
  src/main/java/umc/th/juinjang/controller/ChecklistController.java
  src/main/java/umc/th/juinjang/controller/RecordController.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#77 [refactor/#67] : gradle.yml 수정
  .github/workflows/gradle.yml
Labels: 🌏 deploy, 진, 👊🏻 PULL REQUEST

#78 [refactor/#67] gradle.yml 수정
  .github/workflows/gradle.yml
Labels: 🌏 deploy, 진
