Repository Juinjang/Spring, pull requests merged in 2024-06, with the labels that each got.

#158 [feat/#157] 임장 상세보기에 checkListVersion 추가
  src/main/java/umc/th/juinjang/converter/limjang/LimjangDetailConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangDetailResponseDTO.java
  src/main/java/umc/th/juinjang/model/dto/limjang/enums/LimjangCheckListVersionEnum.java
  src/main/java/umc/th/juinjang/utils/LimjangUtil.java
Labels: ✨ feature, ♻️ refactor, 진, 👊🏻 PULL REQUEST

#160 refactor: change delete and save logic
  src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
Labels: ♻️ refactor, 코난

#161 [test/#141] test 코드 try
  src/test/java/umc/th/juinjang/config/TestConfig.java
  src/test/java/umc/th/juinjang/repository/limjang/LimjangFixture.java
  src/test/java/umc/th/juinjang/repository/limjang/LimjangQuerydslTest.java
  src/test/java/umc/th/juinjang/service/LimjangCommandServiceTest.java
Labels: ✅ test, 진, 👊🏻 PULL REQUEST

#163 [refactor/#162] limjangCommandService 리팩토링
  src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/controller/LimjangController.java
  src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangDetailConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangMainListConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangPostConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/converter/limjang/LimjangUpdateConverter.java
  src/main/java/umc/th/juinjang/model/dto/limjang/LimjangUpdateRequestDTO.java
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/model/entity/LimjangPrice.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangPriceRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepositoryImpl.java
  src/main/java/umc/th/juinjang/service/ImageService/ImageQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangPriceBridge.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangRetriever.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#166 [refactor/#165] 임장 전체 조회 API 리팩토링
  src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepository.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepositoryImpl.java
  src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST
