Repository Juinjang/Spring, pull requests merged in 2025-04, with the labels that each got.

#320 [feat/#318] 임장 생성 API 작업
  src/main/java/umc/th/juinjang/api/address/service/AddressUpdater.java
  src/main/java/umc/th/juinjang/api/limjang/controller/NoteControllerV2.java
  src/main/java/umc/th/juinjang/api/limjang/controller/request/NotePostRequest.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteCommandServiceV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/NotePriceUpdater.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteUpdater.java
  src/main/java/umc/th/juinjang/common/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Address.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Limjang.java
  src/main/java/umc/th/juinjang/domain/limjang/repository/AddressRepository.java
  src/main/java/umc/th/juinjang/domain/limjang/repository/NotePriceFactory.java
  src/main/java/umc/th/juinjang/domain/member/model/Member.java
  src/main/java/umc/th/juinjang/domain/note/liked/model/LikedNote.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
  src/main/java/umc/th/juinjang/domain/pencil/used/model/UsedPencil.java
  src/main/java/umc/th/juinjang/domain/pencilaccount/model/PencilAccount.java
Labels: ✨ feature, 🐞 bugFix, 진, 👊🏻 PULL REQUEST

#330 [feat/#310] 멤버에 한 줄 소개 및 연필 추가
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/api/auth/service/OAuthService.java
  src/main/java/umc/th/juinjang/api/member/controller/MemberController.java
  src/main/java/umc/th/juinjang/api/member/controller/request/IntroductionPatchRequest.java
  src/main/java/umc/th/juinjang/api/member/controller/request/MemberRequestDto.java
  src/main/java/umc/th/juinjang/api/member/service/MemberService.java
  src/main/java/umc/th/juinjang/api/member/service/response/MemberResponseDto.java
  src/main/java/umc/th/juinjang/api/pencilAccount/controller/PencilAccountController.java
  src/main/java/umc/th/juinjang/api/pencilAccount/service/PencilAccountFinder.java
  src/main/java/umc/th/juinjang/api/pencilAccount/service/PencilAccountService.java
  src/main/java/umc/th/juinjang/api/pencilAccount/service/response/PencilQuantityGetResponse.java
  src/main/java/umc/th/juinjang/common/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/common/exception/ExceptionAdvice.java
  src/main/java/umc/th/juinjang/common/exception/handler/PencilAccountHandler.java
  src/main/java/umc/th/juinjang/config/JpaConfig.java
  src/main/java/umc/th/juinjang/domain/member/model/Member.java
  src/main/java/umc/th/juinjang/domain/member/repository/MemberRepository.java
  src/main/java/umc/th/juinjang/domain/pencilaccount/model/PencilAccount.java
  src/main/java/umc/th/juinjang/domain/pencilaccount/repository/PencilAccountRepository.java
  src/test/java/umc/th/juinjang/api/member/service/MemberServiceTest.java
  src/test/java/umc/th/juinjang/api/pencilAccount/controller/PencilAccountControllerTest.java
  src/test/java/umc/th/juinjang/api/pencilAccount/service/PencilAccountServiceTest.java
  src/test/java/umc/th/juinjang/domain/member/model/MemberTest.java
Labels: ✨ feature

#329 [feat/#321] 마이노트 - 임장 목록 조회 API
  src/main/java/umc/th/juinjang/api/limjang/controller/NoteControllerV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteFinder.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/response/UserNotesGetResponse.java
  src/main/java/umc/th/juinjang/api/scrap/service/ScarpFinder.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Address.java
  src/main/java/umc/th/juinjang/domain/limjang/model/LimjangPrice.java
  src/main/java/umc/th/juinjang/domain/limjang/repository/LimjangQueryDslRepository.java
  src/main/java/umc/th/juinjang/domain/limjang/repository/LimjangQueryDslRepositoryImpl.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#338 [feat/#318] 닉네임 중복여부 API 구현
  src/main/java/umc/th/juinjang/api/member/controller/MemberController.java
  src/main/java/umc/th/juinjang/api/member/service/MemberService.java
  src/main/java/umc/th/juinjang/auth/config/SecurityConfig.java
  src/main/java/umc/th/juinjang/domain/member/repository/MemberRepository.java
  src/test/java/umc/th/juinjang/api/member/controller/MemberControllerTest.java
  src/test/java/umc/th/juinjang/api/member/service/MemberServiceTest.java
  src/test/java/umc/th/juinjang/testutil/fixture/MemberFixture.java
Labels: ✨ feature

#339 [feat/#322] 임장 리스트 - 공유하기 선택 API 구현
  src/main/java/umc/th/juinjang/api/image/service/ImageFinder.java
  src/main/java/umc/th/juinjang/api/limjang/controller/NoteControllerV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteFinder.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/response/UserNotesShareableGetResponse.java
  src/main/java/umc/th/juinjang/domain/image/repository/ImageQueryDslRepository.java
  src/main/java/umc/th/juinjang/domain/image/repository/ImageQueryDslRepositoryImpl.java
  src/main/java/umc/th/juinjang/domain/image/repository/ImageRepository.java
  src/main/java/umc/th/juinjang/domain/limjang/repository/LimjangRepository.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#340 [feat/#323] 임장 노트 상세보기(내 임장) API 구현
  src/main/java/umc/th/juinjang/api/limjang/controller/NoteControllerV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/response/UserNoteGetResponse.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#332 [feat/#317] 마이노트 - 상세 - 체크리스트 조회 API
  .gitignore
  src/main/java/umc/th/juinjang/api/checklist/controller/ChecklistControllerV2.java
  src/main/java/umc/th/juinjang/api/checklist/service/ChecklistAnswerFinder.java
  src/main/java/umc/th/juinjang/api/checklist/service/ChecklistQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/checklist/service/response/ChecklistAnswerResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ feature, 코난, 👊🏻 PULL REQUEST

#352 [feat/#342] 공유임장 조회 구현
  build.gradle
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/api/limjang/service/LimjangSchedulerService.java
  src/main/java/umc/th/juinjang/api/note/liked/service/LikedNoteFinder.java
  src/main/java/umc/th/juinjang/api/note/shared/controller/SharedNoteController.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteFinder.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteQueryService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteUpdater.java
  src/main/java/umc/th/juinjang/api/note/shared/service/ViewCountSyncScheduler.java
  src/main/java/umc/th/juinjang/api/note/shared/service/response/SharedNoteGetResponse.java
  src/main/java/umc/th/juinjang/api/pencil/service/UsedPencilFinder.java
  src/main/java/umc/th/juinjang/common/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/common/redis/RedisKeyFactory.java
  src/main/java/umc/th/juinjang/config/RedisConfig.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Address.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Limjang.java
  src/main/java/umc/th/juinjang/domain/note/liked/model/repository/LikedNoteRepository.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
  src/main/java/umc/th/juinjang/domain/pencil/used/repository/UsedPencilRepository.java
Labels: 진
