Repository Juinjang/Spring, pull requests merged in 2025-06, with the labels that each got.

#369 feat : 공유 중단하기 API close #337
  src/main/java/umc/th/juinjang/api/note/shared/controller/SharedNoteController.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteFinder.java
  src/main/java/umc/th/juinjang/common/code/status/SuccessStatus.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
Labels: ✨ feature, 수필씨

#392 [fix/#389] 공유된 임장은 필터링되도록 Fix
  .gitignore
  src/main/java/umc/th/juinjang/api/limjang/service/NoteFinder.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteFinder.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
Labels: 🐞 bugFix, 진, 👊🏻 PULL REQUEST

#402 🐛 fix: fix conflicts
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
Labels: 🔥 hotFix, 코난

#407 [fix/#406] 조회수 NPE fix
  src/main/java/umc/th/juinjang/api/note/shared/service/ViewCountService.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
Labels: 🐞 bugFix, 진, 👊🏻 PULL REQUEST

#413 [fix/#412] 공유노트 생성시 좋아요 수 0으로 설정
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
Labels: 🐞 bugFix, 진

#418 [fix/#417] sharedNote에 price 필드값 업데이트
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
Labels: 🐞 bugFix, 코난

#420 🐛 fix: category field add
  src/main/java/umc/th/juinjang/api/checklist/service/converter/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/api/checklist/service/response/ChecklistAnswerResponseDTO.java
Labels: 🔥 hotFix, 코난

#426 [feat/#425] sql도 대시보드로 확인할 수 있도록 설정 추가 및 로그 포맷팅
  src/main/java/umc/th/juinjang/monitoring/ApiFilterConfig.java
  src/main/java/umc/th/juinjang/monitoring/ApiLogRequestLogGenerator.java
  src/main/java/umc/th/juinjang/monitoring/ApiLogResponseGenerator.java
  src/main/java/umc/th/juinjang/monitoring/ApiLoggerFilter.java
  src/main/resources/logback-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST
