Repository Juinjang/Spring, pull requests merged in 2025-01, with the labels that each got.

#269 [feat/#268] 디스코드 알림 전송 이벤트 퍼블리셔 방식으로 변경
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/event/SignUpEvent.java
  src/main/java/umc/th/juinjang/event/publisher/ApplicationMemberEventPublisherAdapter.java
  src/main/java/umc/th/juinjang/event/publisher/MemberEventPublisher.java
  src/main/java/umc/th/juinjang/event/subscriber/DiscordEventListener.java
  src/main/java/umc/th/juinjang/event/subscriber/EventMessage.java
  src/main/java/umc/th/juinjang/external/discord/DiscordAlertProvider.java
  src/main/java/umc/th/juinjang/external/discord/StatusMessage.java
  src/main/java/umc/th/juinjang/external/discord/dto/DiscordAlert.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: 진

#273 [feat/#271] 약관 정보 전송 API
  src/main/java/umc/th/juinjang/controller/MemberController.java
  src/main/java/umc/th/juinjang/model/dto/member/MemberAgreeVersionPostRequest.java
  src/main/java/umc/th/juinjang/model/entity/Member.java
  src/main/java/umc/th/juinjang/service/MemberService/MemberService.java
Labels: ➕ add, ✨ feature, 진, 👊🏻 PULL REQUEST

#275 [refactor/#272] add version info Apple Login & Signup DTO
  src/main/java/umc/th/juinjang/controller/OAuthController.java
  src/main/java/umc/th/juinjang/model/dto/auth/LoginResponseVersion2Dto.java
  src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleSignUpRequestVersion2Dto.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
Labels: ♻️ refactor, 시니

#274 [ feat/#271] 약관 동의 버전 API를 POST를 PATCH로 변경
  src/main/java/umc/th/juinjang/controller/MemberController.java
Labels: 진

#276 [feat/#270] 로깅 파일 추가
  src/main/resources/logback-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: ➕ add, 진

#277 [refactor/#270] 로그파일 수정
  src/main/resources/logback-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#283 refactor(#282): add kakao, apple Ver2 URL in SecurityConfig
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
Labels: ♻️ refactor, 시니

#284 [deploy] prod 서버에 반영
  README.md
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
  src/main/java/umc/th/juinjang/controller/MemberController.java
  src/main/java/umc/th/juinjang/controller/OAuthController.java
  src/main/java/umc/th/juinjang/event/SignUpEvent.java
  src/main/java/umc/th/juinjang/event/publisher/ApplicationMemberEventPublisherAdapter.java
  src/main/java/umc/th/juinjang/event/publisher/MemberEventPublisher.java
  src/main/java/umc/th/juinjang/event/subscriber/DiscordEventListener.java
  src/main/java/umc/th/juinjang/event/subscriber/EventMessage.java
  src/main/java/umc/th/juinjang/external/discord/DiscordAlertProvider.java
  src/main/java/umc/th/juinjang/external/discord/StatusMessage.java
  src/main/java/umc/th/juinjang/external/discord/dto/DiscordAlert.java
  src/main/java/umc/th/juinjang/model/dto/auth/LoginResponseVersion2Dto.java
  src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleSignUpRequestVersion2Dto.java
  src/main/java/umc/th/juinjang/model/dto/auth/kakao/KakaoSignUpRequestVersion2Dto.java
  src/main/java/umc/th/juinjang/model/dto/member/MemberAgreeVersionPostRequest.java
  src/main/java/umc/th/juinjang/model/entity/Member.java
  src/main/java/umc/th/juinjang/service/MemberService/MemberService.java
  src/main/java/umc/th/juinjang/service/auth/OAuthService.java
  src/main/resources/logback-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: 🌏 deploy

#285 refactor(#282): ver2 apple signup & login in prod
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
Labels: ♻️ refactor

#286 [deploy] prod 서버에 반영
  src/main/java/umc/th/juinjang/config/SecurityConfig.java
Labels: 🌏 deploy

#291 [feat#290] 토큰 만료 시간 yml에서 주입하도록 변경
  src/main/java/umc/th/juinjang/service/auth/JwtService.java
Labels: 진, 👊🏻 PULL REQUEST
