Repository Juinjang/Spring, pull requests merged in 2025-07, with the labels that each got.

#429 🐛 fix: safe search log 추가
  src/main/java/umc/th/juinjang/external/safeSearch/SafeSearchClient.java
Labels: 🐞 bugFix, 코난

#433 [feat/#432] 이미지 없을 시 null이 아닌 빈배열 return
  src/main/java/umc/th/juinjang/api/note/shared/service/response/SharedNoteGetResponse.java
  src/main/java/umc/th/juinjang/event/subscriber/DiscordEventListener.java
Labels: 진, 👊🏻 PULL REQUEST

#436 [fix/#435] 임장 시기 리턴하는 로직 fix
  src/main/java/umc/th/juinjang/api/note/shared/service/response/SharedNoteGetResponse.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
Labels: 🐞 bugFix, 진

#439 [feat/#434] 조회수 버그 fix 및 로직 변경
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteQueryService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteUpdater.java
  src/main/java/umc/th/juinjang/api/note/shared/service/ViewCountService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/ViewCountSyncScheduler.java
  src/main/java/umc/th/juinjang/api/reward/service/RewardService.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
  src/main/java/umc/th/juinjang/event/subscriber/RewardViewCountEventListener.java
Labels: ✨ feature, 🐞 bugFix, 진, 👊🏻 PULL REQUEST
