Repository Juinjang/Spring, pull requests merged in 2025-02, with the labels that each got.

#298 [fix/#297]: record Delete API
  src/main/java/umc/th/juinjang/service/record/RecordService.java
Labels: 🔥 hotFix

#299 [deploy] dev > prod
  src/main/java/umc/th/juinjang/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/th/juinjang/config/ApiFilterConfig.java
  src/main/java/umc/th/juinjang/controller/monitoring/APILoggerFilter.java
  src/main/java/umc/th/juinjang/controller/monitoring/APILoggerGenerator.java
  src/main/java/umc/th/juinjang/controller/monitoring/APILoggerPrinter.java
  src/main/java/umc/th/juinjang/controller/monitoring/APIRequestLoggerGenerator.java
  src/main/java/umc/th/juinjang/controller/monitoring/APIResponseLoggerGenerator.java
  src/main/java/umc/th/juinjang/controller/monitoring/CustomContentCachingHttpRequestWrapper.java
  src/main/java/umc/th/juinjang/service/auth/JwtService.java
  src/main/java/umc/th/juinjang/service/record/RecordService.java
  src/main/java/umc/th/juinjang/utils/LoggerProvider.java
  src/main/resources/logback-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: 🌏 deploy

#307 [refactor/#267] 이미지 service 관련 리팩
  src/main/java/umc/th/juinjang/controller/ImageController.java
  src/main/java/umc/th/juinjang/converter/image/ImageListConverter.java
  src/main/java/umc/th/juinjang/converter/image/ImageUploadConverter.java
  src/main/java/umc/th/juinjang/model/dto/image/ImagesGetResponse.java
  src/main/java/umc/th/juinjang/model/entity/Image.java
  src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java
  src/main/java/umc/th/juinjang/service/external/S3Service.java
  src/main/java/umc/th/juinjang/service/image/ImageCommandService.java
  src/main/java/umc/th/juinjang/service/image/ImageCommandServiceImpl.java
  src/main/java/umc/th/juinjang/service/image/ImageQueryService.java
  src/main/java/umc/th/juinjang/service/image/ImageQueryServiceImpl.java
  src/main/java/umc/th/juinjang/service/limjang/LimjangQueryServiceImpl.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST

#309 [refac/#243] 임장 엔티티에서 where 어노테이션 제거
  src/main/java/umc/th/juinjang/model/entity/Limjang.java
  src/main/java/umc/th/juinjang/service/image/ImageCommandServiceImpl.java
Labels: ♻️ refactor, 진, 👊🏻 PULL REQUEST
