Repository Juinjang/Spring, pull requests merged in 2025-05, with the labels that each got.

#354 [feat/#324,#325,#326] 연필 관련 API 구현 (얻은/구매한/사용한 연필 목록)
  build.gradle
  src/main/java/umc/th/juinjang/api/pencil/controller/PencilController.java
  src/main/java/umc/th/juinjang/api/pencil/service/AcquiredPencilFinder.java
  src/main/java/umc/th/juinjang/api/pencil/service/PencilService.java
  src/main/java/umc/th/juinjang/api/pencil/service/PurchasedPencilFinder.java
  src/main/java/umc/th/juinjang/api/pencil/service/UsedPencilFinder.java
  src/main/java/umc/th/juinjang/api/pencil/service/response/AcquiredPencilResponse.java
  src/main/java/umc/th/juinjang/api/pencil/service/response/PurchasedPencilResponse.java
  src/main/java/umc/th/juinjang/api/pencil/service/response/UsedPencilResponse.java
  src/main/java/umc/th/juinjang/domain/common/BaseEntity.java
  src/main/java/umc/th/juinjang/domain/pencil/acquired/model/AcquiredPencil.java
  src/main/java/umc/th/juinjang/domain/pencil/acquired/repository/AcquiredPencilRepository.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/model/DeliveryStatus.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/model/DeliveryStatusConverter.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/model/PurchasedPencil.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/repository/PurchasedPencilRepository.java
  src/main/java/umc/th/juinjang/domain/pencil/used/repository/UsedPencilRepository.java
  src/test/java/umc/th/juinjang/api/ControllerTestSupport.java
  src/test/java/umc/th/juinjang/api/IntegrationTestSupport.java
  src/test/java/umc/th/juinjang/api/member/service/MemberServiceTest.java
  src/test/java/umc/th/juinjang/api/pencil/service/PencilServiceTest.java
  src/test/java/umc/th/juinjang/api/pencilAccount/controller/PencilAccountControllerTest.java
  src/test/java/umc/th/juinjang/api/pencilAccount/service/PencilAccountServiceTest.java
Labels: ✨ feature

#358 [feat/#333] 마이노트 상세 - 리포트 조회
  src/main/java/umc/th/juinjang/api/checklist/controller/ChecklistControllerV2.java
  src/main/java/umc/th/juinjang/api/checklist/service/ChecklistAnswerFinder.java
  src/main/java/umc/th/juinjang/api/checklist/service/ChecklistQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/checklist/service/ReportFinder.java
  src/main/java/umc/th/juinjang/api/checklist/service/converter/ChecklistAnswerAndReportConverter.java
  src/main/java/umc/th/juinjang/api/checklist/service/converter/ReportConverter.java
  src/main/java/umc/th/juinjang/api/checklist/service/response/ReportResponseDTO.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteFinder.java
Labels: ✨ feature, 코난

#367 [feat/#362] 공유 중단된 노트들 조건에 따라 조건문 처리
  src/main/java/umc/th/juinjang/api/note/liked/service/LikedNoteFinder.java
  src/main/java/umc/th/juinjang/domain/note/liked/model/repository/LikedNoteQueryDSLRepository.java
  src/main/java/umc/th/juinjang/domain/note/liked/model/repository/LikedNoteQueryDSLRepositoryImpl.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteQueryDSLRepositoryImpl.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#365 feat: 얻은 연필 읽음 처리 하는 API 구현 완료
  src/main/java/umc/th/juinjang/api/pencil/controller/PencilController.java
  src/main/java/umc/th/juinjang/api/pencil/service/PencilCommandService.java
  src/main/java/umc/th/juinjang/api/pencil/service/PencilQueryService.java
  src/main/java/umc/th/juinjang/domain/pencil/acquired/model/AcquiredPencil.java
  src/test/java/umc/th/juinjang/api/pencil/service/PencilServiceTest.java
Labels: ✨ feature, 👊🏻 PULL REQUEST

#361 [fix/#357] 구매 연필 사용 시 PurchasedPencil에도 반영되도록 fix
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/api/pencil/service/PurchasedPencilUpdater.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/model/PurchasedPencil.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/repository/PurchasedPencilRepository.java
Labels: 🐞 bugFix, 진, 👊🏻 PULL REQUEST

#372 [fix/#371] 공유 중단된 노트 조회하지 않도록 조건문 처리
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteQueryDSLRepositoryImpl.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#370 [feat/#366] 조회수 리워드 구현
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteFinder.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteQueryService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/ViewCountService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/ViewCountSyncScheduler.java
  src/main/java/umc/th/juinjang/api/reward/service/RewardFinder.java
  src/main/java/umc/th/juinjang/api/reward/service/RewardService.java
  src/main/java/umc/th/juinjang/api/reward/service/RewardUpdater.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/ViewCountPolicy.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
  src/main/java/umc/th/juinjang/domain/pencil/acquired/model/AcquiredType.java
  src/main/java/umc/th/juinjang/domain/reward/model/Reward.java
  src/main/java/umc/th/juinjang/domain/reward/model/RewardType.java
  src/main/java/umc/th/juinjang/domain/reward/repository/RewardRepository.java
  src/main/java/umc/th/juinjang/event/RewardViewCountEvent.java
  src/main/java/umc/th/juinjang/event/publisher/ApplicationRewardViewCountPublisherAdapter.java
  src/main/java/umc/th/juinjang/event/publisher/RewardViewCountPublisher.java
  src/main/java/umc/th/juinjang/event/subscriber/RewardViewCountEventListener.java
Labels: ✨ feature, 진, 👊🏻 PULL REQUEST

#374 [feat/#334] 공유 조건 충족 여부 조회 API
  .gitignore
  src/main/java/umc/th/juinjang/api/checklist/service/ChecklistAnswerFinder.java
  src/main/java/umc/th/juinjang/api/limjang/controller/NoteControllerV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/NoteQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/response/ChecklistConditionResponse.java
Labels: ✨ feature, 코난

#376 [fix/#375] limjang entity에 isSharable 필드 추가
  src/main/java/umc/th/juinjang/domain/limjang/model/Limjang.java
Labels: 🔥 hotFix, 코난

#359 [feat/#336] safe search 및 노트 공유하기 API
  .gitignore
  build.gradle
  src/main/java/umc/th/juinjang/api/limjang/service/NoteUpdater.java
  src/main/java/umc/th/juinjang/api/note/shared/controller/SharedNoteController.java
  src/main/java/umc/th/juinjang/api/note/shared/controller/request/SharedNotePostRequest.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteFinder.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteUpdater.java
  src/main/java/umc/th/juinjang/api/pencilAccount/service/PencilAccountUpdater.java
  src/main/java/umc/th/juinjang/common/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Limjang.java
  src/main/java/umc/th/juinjang/domain/note/shared/model/SharedNote.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
  src/main/java/umc/th/juinjang/safeSearch/SafeSearchClient.java
Labels: ✨ feature, 코난

#382 [refactor/#377] checklist 답변 생성 및 수정시 isSharable 업데이트 추가
  src/main/java/umc/th/juinjang/api/checklist/controller/ChecklistControllerV2.java
  src/main/java/umc/th/juinjang/api/checklist/service/ChecklistCommandServiceV2.java
  src/main/java/umc/th/juinjang/api/note/shared/controller/SharedNoteController.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteCommandService.java
  src/main/java/umc/th/juinjang/common/code/status/ErrorStatus.java
  src/main/java/umc/th/juinjang/domain/limjang/model/Limjang.java
  src/main/java/umc/th/juinjang/external/safeSearch/SafeSearchClient.java
Labels: ♻️ refactor, 코난

#383 [feat/#335] SharedNote 구매시 리뷰 + 체크리스트 보이도록, 구매하지 않았을 시 체크리스트만 보이도록 하는 조회 API
  src/main/java/umc/th/juinjang/api/note/shared/controller/SharedNoteController.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteQueryService.java
  src/main/java/umc/th/juinjang/api/note/shared/service/response/SharedNoteCheckListAndReviewResponse.java
Labels: ✨ feature, 코난

#381 [feat/#327] 연필 구매하기 API 구현
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  build.gradle
  src/main/java/umc/th/juinjang/JuinjangApplication.java
  src/main/java/umc/th/juinjang/api/apple/controller/AppleController.java
  src/main/java/umc/th/juinjang/api/apple/service/AppleService.java
  src/main/java/umc/th/juinjang/api/apple/service/command/AppleTransactionVerifyCommand.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteQueryService.java
  src/main/java/umc/th/juinjang/api/pencil/controller/PencilController.java
  src/main/java/umc/th/juinjang/api/pencil/controller/request/AppleIAPPurchaseRequest.java
  src/main/java/umc/th/juinjang/api/pencil/service/PencilCommandService.java
  src/main/java/umc/th/juinjang/api/pencil/service/PurchasedPencilFinder.java
  src/main/java/umc/th/juinjang/api/pencil/service/PurchasedPencilUpdater.java
  src/main/java/umc/th/juinjang/api/pencil/service/response/AppleIAPPurchaseResponse.java
  src/main/java/umc/th/juinjang/api/pencil/service/response/PurchasedPencilResponse.java
  src/main/java/umc/th/juinjang/api/pencil/service/response/VerificationResult.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/model/PurchasedPencil.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/model/TransactionStatus.java
  src/main/java/umc/th/juinjang/domain/pencil/purchased/repository/PurchasedPencilRepository.java
  src/main/java/umc/th/juinjang/domain/pencilaccount/model/PencilAccount.java
  src/test/java/umc/th/juinjang/api/ControllerTestSupport.java
  src/test/java/umc/th/juinjang/api/pencil/service/PencilCommandServiceTest.java
  src/test/java/umc/th/juinjang/api/pencil/service/PencilQueryServiceTest.java
  src/test/java/umc/th/juinjang/repository/limjang/LimjangQuerydslTest.java
Labels: ✨ feature, 수필씨

#391 [feat/#390] 임장 상세 API에서 공유된 임장인지 판별하는 필드값 추가
  src/main/java/umc/th/juinjang/api/limjang/service/NoteQueryServiceV2.java
  src/main/java/umc/th/juinjang/api/limjang/service/response/UserNoteGetResponse.java
  src/main/java/umc/th/juinjang/api/note/shared/service/SharedNoteFinder.java
  src/main/java/umc/th/juinjang/domain/note/shared/repository/SharedNoteRepository.java
Labels: ✨ feature, 진
